### ISSUE TITLE
Can't get achievements

### ISSUE THREAD

**Issue by Shqrp** [slothpixel/ui#183]
![image](https://user-images.githubusercontent.com/32310370/97844759-e03e3e80-1ceb-11eb-9579-c0414cd8e483.png)

Hello there,

this is what I see whenever I open the page `http://localhost:3000/players/Shqrp_/achievements`

Thanks!

**Comment by builder-247** [comment]
Hey!

This can be fixed by localy updating your `hypixelconstants`, you can do this by running
`cd node_modules/hypixelconstants`
`npm run build`
and restarting the react app.
