### ISSUE TITLE
Fix alignment of Medium social media icon

### ISSUE THREAD

**Issue by builder-247** [slothpixel/ui#2]
The Medium logo  on footer isn't correctly aligned with rest of the social media icons.

![image](https://user-images.githubusercontent.com/14019974/47916160-e6577580-dead-11e8-886c-caf74967a2af.png)

Relevant files
* [Medium.jsx](https://github.com/slothpixel/ui/blob/master/src/components/Icons/Medium.jsx)
* [Footer.jsx](https://github.com/slothpixel/ui/blob/master/src/components/Footer/Footer.jsx)

**Comment by OlenaVyshnevska** [comment]
Hi, is it ok for me to work on this one?
